### ISSUE TITLE
Update devcontainer for Docker builds

### ISSUE THREAD

**Issue by nomiro** [doitintl/docops-containers#3]
With the current devcontainer configuration, there are two issues:

- The base image uses Debian, but the stock GitHub [Docker workflow](https://github.com/actions/starter-workflows/blob/7b64f441651d3005d0849daa72311c22052441d6/ci/docker-image.yml) uses Ubuntu.

- The base image does not come with any Docker tools installed, and it seems impossible to install them with APT.

Potential solution:

- The stock VSCode [devcontainer image library](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/) includes a number of Docker-specific images that may be of use. I am not sure which one is the most appropriate yet.

**Comment by norosa** [comment]
See also:

- https://github.com/doitintl/docops-gitbook-client/issues/12

**Comment by nomiro** [comment]
No longer an issue.
